name: Docker Push Status

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/api/webhook/*'
      - 'Dockerfile'
      - 'next.config.js'
      - 'package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/api/webhook/*'
      - 'Dockerfile'
      - 'next.config.js'
      - 'package.json'
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/plexfm:latest
            ghcr.io/${{ github.repository_owner }}/plexfm:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/plexfm:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/plexfm:buildcache,mode=max
           
