name: Docker Push Status

on:
  push:
    branches: [ "main" ]
    paths:
      - 'public/index.html'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'public/index.html'
  workflow_dispatch:
  
jobs:
  deploy:
  working-directory: ./public
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
